/**
 * TypeScript Hello World program in node.js
 *
 * First, create a new directory to store the code, e.g., helloworld.
 * Second, launch VS Code and open that directory.
 * Third, create a new TypeScript file called app.ts. The extension of a TypeScript file is .ts.
 * Fourth, type the following source code in the app.ts file
 */

let message: string = 'Hello, World!';
console.log(message);

/**
 * Sixth, type the following command on the Terminal to compile the app.ts file:
 *
 * If everything is fine, you’ll see a new file called app.js is generated by
 *  the TypeScript compiler.
 *
 * To run the app.js file in node.js, you use the following command:
 *
 *  node app.js
 *
 * If you installed the ts-node module mentioned in the setting up TypeScript development
 *  environment, you can use just one command to compile the TypeScript file and
 *  execute the output file in one shot.
 *
 *  ts-node app.ts
 *
 *
 * The TypeScript compiler will generate a new app.js file,
 *  and the Live Server will automatically reload it on the web browser.
 */